### ISSUE TITLE
No module named 'tensorflow.keras'

### ISSUE THREAD

**Issue by sarahhp** [jaydu1/VITAE#8]
I installed pyvitae through mamba on a unix system and found this error: No module named 'tensorflow.keras'.  

Turns out the keras package was upgraded beyond tensorflow [ aka keras v3.4.1 and tensorflow 2.16.2].  It seems that keras is missing version 2.16 is missing from conda-forge ? 

Downgrading tensorflow to v2.15 fixes the issue.  I hope this helps someone :)

**Comment by jaydu1** [comment]
Thanks for reporting the dependency issue. 

Tensorflow has recently released a new version [v2.16](https://blog.tensorflow.org/2024/03/whats-new-in-tensorflow-216.html), which uses Keras v3.
Although there are options to use Keras v2 (conda package [https://anaconda.org/conda-forge/tf-keras](tf-keras)) given in the previous link, we recommend using an older version of Tensorflow (<= v2.15) to avoid the troublesome.
